#name: Build & Deploy
#on:
#  push:
#    branches: [tui]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy NodeJS app
#        uses: appleboy/ssh-action@v0.1.2
#        with:
#          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
#          key: ${{secrets.SSH_KEY}} # Private or public key of the server
#          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
#
#          script: |
#            cd /
#            rm -rf /var/www/main/
#            rm -rf /home/cloned-repo-main/
#            cd /var/www
#            mkdir main
#            cd /home
#            mkdir cloned-repo-main
#            cd cloned-repo-main
#            git clone https://github.com/Andrii-Yukhymenko/Andrii-Yukhymenko-Site.git
#            cd Andrii-Yukhymenko-Site/
#            cp -r app/* /var/www/main
