name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            cd /
            sudo rm -rf /var/www/main/
            sudo rm -rf /home/cloned-main/
            cd /var/www
            sudo mkdir main
            cd /home
            sudo mkdir cloned-main
            cd cloned-main
            sudo git clone https://github.com/Andrii-Yukhymenko/Andrii-Yukhymenko-Site-TUI.git
            cd Andrii-Yukhymenko-Site-TUI/
            sudo yarn install
            sudo yarn build
            sudo cp -r build/* /var/www/main
